version: '3.1'

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./docker-data/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.10-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - 5672:5672 # AMQP protocol port
            - 15672:15672 # HTTP management UI
