version: '3.1'

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./docker-data/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin

    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./docker-data/redis_data:/data
