services:
    product-server:
        image: product-microservices_product-server
        deploy:
            mode: replicated
            replicas: 2

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx_config:/etc/nginx/conf.d
        depends_on:
            - product-server
        ports:
            - 3000:8000
