# Build
FROM node:14-alpine

WORKDIR /app
COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build

# Start
FROM node:14-alpine
ENV NODE_ENV production

WORKDIR /app
COPY package*.json ./

RUN npm ci --only=production && npm cache clean --force
COPY --from=0 /app/dist ./dist

EXPOSE 8000
CMD ["npm", "start"]



# COPY tsconfig.json ./
